import Foundation

enum L10n {
    static func t(_ key: String, _ language: AppLanguage) -> String {
        table[language]?[key] ?? table[.english]?[key] ?? key
    }

    private static let table: [AppLanguage: [String: String]] = [
        .english: [
            "quickStart": "Quick Start",
            "settings": "Settings",
            "history": "History",
            "quit": "Quit",
            "original": "Original",
            "translation": "Translation",
            "copy": "Copy",
            "replace": "Replace",
            "speak": "Speak",
            "openSettings": "Open Settings",
            "needsAttention": "Needs attention",
            "working": "Working",
            "translating": "Translating...",
            "emptySelection": "No selected text found",
            "emptySelectionHelp": "Select text anywhere on your Mac, then press the JellyTranslate hotkey.",
            "testMode": "For testing only. Does not perform real translation.",
            "test": "Test",
            "permissionNeeded": "Permission needed",
            "permissionNeededMessage": "Accessibility permission is not active for this build of JellyTranslate. Remove old JellyTranslate entries from Privacy & Security, then add the built JellyTranslate.app or enable Xcode while running from Xcode.",
            "copyFallbackFailed": "Copy fallback did not work",
            "noSelectedText": "No selected text",
            "providerTimeout": "Provider timeout",
            "providerSetup": "Provider needs setup",
            "translationFailed": "Translation failed",
            "welcomeTitle": "Welcome to JellyTranslate",
            "welcomeText": "Select text anywhere on your Mac, press the hotkey, and get an instant translation.",
            "welcomeNote": "No accounts, no tour. Just the few things needed for the hotkey flow.",
            "permissions": "Permissions",
            "permissionsText": "JellyTranslate uses Accessibility permission to read selected text and replace text when possible. Clipboard fallback may still work in some apps.",
            "accessibility": "Accessibility",
            "granted": "Granted",
            "notGranted": "Not granted",
            "openPrivacy": "Open Privacy & Security Settings",
            "provider": "Provider",
            "providerText": "MyMemory is ready for free testing without an API key. OpenAI remains optional and stores its key locally in macOS Keychain.",
            "openAIKey": "OpenAI API key",
            "saveKey": "Save Key",
            "keyStored": "Your key is stored locally in macOS Keychain.",
            "customInSettings": "Custom provider details live in Settings > Advanced.",
            "tryIt": "Try it",
            "tryItText": "Highlight any text and press the hotkey to translate.",
            "privacyShort": "Selected text is sent only to your chosen translation provider when you trigger translation. API keys are stored in macOS Keychain.",
            "back": "Back",
            "continue": "Continue",
            "finish": "Finish",
            "translationSettings": "Translation",
            "targetLanguage": "Target language",
            "hotkey": "Hotkey",
            "primaryHotkey": "Show translation",
            "secondaryHotkey": "Translate and replace",
            "resetHotkeys": "Reset hotkeys",
            "recordHotkey": "Press shortcut...",
            "behavior": "Behavior",
            "saveHistory": "Save history",
            "showPopupNearCursor": "Show popup near cursor",
            "closeAfterCopy": "Close popup after copy",
            "clearTranslationHistory": "Clear Translation History",
            "advanced": "Advanced",
            "sourceLanguage": "Source language",
            "launchAtLogin": "Launch at login",
            "customProvider": "Custom Provider",
            "baseURL": "Base URL",
            "path": "Path",
            "model": "Model",
            "privacy": "Privacy",
            "apiKeysKeychain": "API keys are stored in macOS Keychain.",
            "historyLocal": "History is stored locally on this Mac. It is not synced or uploaded by JellyTranslate.",
            "clipboardFallback": "Clipboard is used only as a fallback and is restored when possible.",
            "searchHistory": "Search recent translations",
            "recentTranslations": "Recent translations",
            "clearAll": "Clear All",
            "delete": "Delete",
            "historyOff": "History is off",
            "historyOffHelp": "Enable Save history in Settings to keep recent translations.",
            "noRecentTranslations": "No recent translations",
            "noRecentTranslationsHelp": "Translations you save will appear here.",
            "noResults": "No results",
            "noResultsHelp": "Try a different search.",
            "mock": "Mock",
            "openAI": "OpenAI",
            "custom": "Custom",
            "libreTranslate": "LibreTranslate",
            "libreTranslateKey": "LibreTranslate API key (optional)",
            "libreTranslateHint": "LibreTranslate can work without a key on self-hosted instances. Public instances may require a key or have limits.",
            "libreTranslateProvider": "LibreTranslate Provider",
            "myMemory": "MyMemory",
            "myMemoryHint": "Free provider for everyday MVP testing. No API key required. Add an email to raise the free daily limit; text is still sent to MyMemory only when you translate.",
            "contactEmail": "Contact email",
            "optional": "Optional",
            "deepLComingSoon": "DeepL - Coming soon",
            "appLanguage": "App Language",
            "keySaved": "Key saved",
            "keyCleared": "Key cleared"
        ],
        .russian: [
            "quickStart": "Быстрый старт",
            "settings": "Настройки",
            "history": "История",
            "quit": "Выйти",
            "original": "Оригинал",
            "translation": "Перевод",
            "copy": "Копировать",
            "replace": "Заменить",
            "speak": "Озвучить",
            "openSettings": "Открыть настройки",
            "needsAttention": "Нужно внимание",
            "working": "Работаю",
            "translating": "Перевожу...",
            "emptySelection": "Текст не выделен",
            "emptySelectionHelp": "Выделите текст в любом приложении и нажмите хоткей JellyTranslate.",
            "testMode": "Только для теста. Настоящий перевод не выполняется.",
            "test": "Тест",
            "permissionNeeded": "Нужно разрешение",
            "permissionNeededMessage": "Разрешение Accessibility не активно для этой сборки JellyTranslate. Удалите старые записи JellyTranslate в Privacy & Security, затем добавьте собранный JellyTranslate.app или включите Xcode при запуске из Xcode.",
            "copyFallbackFailed": "Не удалось скопировать текст",
            "noSelectedText": "Текст не выделен",
            "providerTimeout": "Провайдер не ответил",
            "providerSetup": "Настройте провайдер",
            "translationFailed": "Перевод не удался",
            "welcomeTitle": "Добро пожаловать в JellyTranslate",
            "welcomeText": "Выделите текст в любом приложении, нажмите хоткей и сразу получите перевод.",
            "welcomeNote": "Без аккаунтов и длинного тура. Только то, что нужно для перевода по хоткею.",
            "permissions": "Разрешения",
            "permissionsText": "Разрешение нужно, чтобы читать выделенный текст и по возможности заменять его. В некоторых приложениях может сработать fallback через буфер обмена.",
            "accessibility": "Accessibility",
            "granted": "Разрешено",
            "notGranted": "Не разрешено",
            "openPrivacy": "Открыть Privacy & Security",
            "provider": "Провайдер",
            "providerText": "MyMemory готов для бесплатного тестирования без API-ключа. OpenAI остаётся опциональным, ключ хранится локально в macOS Keychain.",
            "openAIKey": "API-ключ OpenAI",
            "saveKey": "Сохранить ключ",
            "keyStored": "Ключ хранится локально в macOS Keychain.",
            "customInSettings": "Custom Provider настраивается в Настройки > Advanced.",
            "tryIt": "Попробуйте",
            "tryItText": "Выделите любой текст и нажмите хоткей, чтобы перевести.",
            "privacyShort": "Выделенный текст отправляется только выбранному провайдеру и только когда вы запускаете перевод. API-ключи хранятся в macOS Keychain.",
            "back": "Назад",
            "continue": "Дальше",
            "finish": "Готово",
            "translationSettings": "Перевод",
            "targetLanguage": "Язык перевода",
            "hotkey": "Хоткеи",
            "primaryHotkey": "Показать перевод",
            "secondaryHotkey": "Перевести и заменить",
            "resetHotkeys": "Сбросить хоткеи",
            "recordHotkey": "Нажмите сочетание...",
            "behavior": "Поведение",
            "saveHistory": "Сохранять историю",
            "showPopupNearCursor": "Показывать popup рядом с курсором",
            "closeAfterCopy": "Закрывать popup после копирования",
            "clearTranslationHistory": "Очистить историю переводов",
            "advanced": "Advanced",
            "sourceLanguage": "Исходный язык",
            "launchAtLogin": "Запускать при входе",
            "customProvider": "Custom Provider",
            "baseURL": "Base URL",
            "path": "Path",
            "model": "Модель",
            "privacy": "Приватность",
            "apiKeysKeychain": "API-ключи хранятся в macOS Keychain.",
            "historyLocal": "История хранится только на этом Mac. JellyTranslate её не синхронизирует и не загружает.",
            "clipboardFallback": "Буфер обмена используется только как fallback и по возможности восстанавливается.",
            "searchHistory": "Поиск по истории",
            "recentTranslations": "Недавние переводы",
            "clearAll": "Очистить всё",
            "delete": "Удалить",
            "historyOff": "История выключена",
            "historyOffHelp": "Включите «Сохранять историю» в настройках, чтобы сохранять новые переводы.",
            "noRecentTranslations": "История пуста",
            "noRecentTranslationsHelp": "Сохранённые переводы появятся здесь.",
            "noResults": "Ничего не найдено",
            "noResultsHelp": "Попробуйте другой запрос.",
            "mock": "Mock",
            "openAI": "OpenAI",
            "custom": "Custom",
            "libreTranslate": "LibreTranslate",
            "libreTranslateKey": "API-ключ LibreTranslate (необязательно)",
            "libreTranslateHint": "LibreTranslate может работать без ключа на self-hosted серверах. Публичные инстансы могут требовать ключ или иметь лимиты.",
            "libreTranslateProvider": "LibreTranslate Provider",
            "myMemory": "MyMemory",
            "myMemoryHint": "Бесплатный провайдер для MVP-тестов. API-ключ не нужен. Email повышает бесплатный дневной лимит; текст отправляется в MyMemory только при переводе.",
            "contactEmail": "Email для лимита",
            "optional": "Необязательно",
            "deepLComingSoon": "DeepL — скоро",
            "appLanguage": "Язык интерфейса",
            "keySaved": "Ключ сохранён",
            "keyCleared": "Ключ удалён"
        ]
    ]
}
