import Foundation

enum L10n {
    static func t(_ key: String, _ language: AppLanguage) -> String {
        table[language]?[key] ?? table[.english]?[key] ?? key
    }

    private static let table: [AppLanguage: [String: String]] = [
        .english: [
            "quickStart": "Quick Start",
            "settings": "Settings",
            "history": "History",
            "quit": "Quit",
            "original": "Original",
            "translation": "Translation",
            "copy": "Copy",
            "replace": "Replace",
            "speak": "Speak",
            "openSettings": "Open Settings",
            "needsAttention": "Needs attention",
            "working": "Working",
            "translating": "Translating...",
            "emptySelection": "No selected text found",
            "emptySelectionHelp": "Select text anywhere on your Mac, then press the JellyTranslate hotkey.",
            "testMode": "For testing only. Does not perform real translation.",
            "test": "Test",
            "permissionNeeded": "Permission needed",
            "permissionNeededMessage": "JellyTranslate needs Accessibility permission to read selected text. Open Privacy & Security and enable JellyTranslate.",
            "copyFallbackFailed": "JellyTranslate could not read the selected text",
            "noSelectedText": "No selected text",
            "providerTimeout": "Provider timeout",
            "providerSetup": "Translation service needs setup",
            "translationFailed": "Translation failed",
            "welcomeTitle": "Welcome to JellyTranslate",
            "welcomeText": "Select text anywhere on your Mac, press the hotkey, and get an instant translation.",
            "welcomeNote": "No accounts, no tour. Just the few things needed for the hotkey flow.",
            "permissions": "Permissions",
            "permissionsText": "JellyTranslate needs a Mac permission to read selected text and replace it when possible.",
            "accessibility": "Accessibility",
            "granted": "Granted",
            "notGranted": "Not granted",
            "openPrivacy": "Open Privacy & Security Settings",
            "checkAgain": "Check again",
            "permissionRefreshHint": "If the switch is already on but this still says Not granted, quit and reopen JellyTranslate. macOS sometimes applies Accessibility after restart.",
            "provider": "Translation service",
            "providerText": "Choose where translations will come from. MyMemory works today without an account; more services are coming soon.",
            "openAIKey": "OpenAI API key",
            "saveKey": "Save Key",
            "keyStored": "Your key is stored locally in secure Mac storage.",
            "customInSettings": "Custom services will be available later.",
            "tryIt": "Try it",
            "tryItText": "Highlight any text and press the hotkey to translate.",
            "privacyShort": "Selected text is sent only when you ask JellyTranslate to translate it.",
            "back": "Back",
            "continue": "Continue",
            "finish": "Finish",
            "translationSettings": "Translation",
            "targetLanguage": "Target language",
            "hotkey": "Hotkey",
            "primaryHotkey": "Show translation",
            "secondaryHotkey": "Translate and replace",
            "resetHotkeys": "Reset hotkeys",
            "recordHotkey": "Press shortcut...",
            "reservedHotkeyWarning": "This is a common macOS shortcut. Choose another combination to avoid surprises.",
            "behavior": "Behavior",
            "saveHistory": "Save history",
            "showPopupNearCursor": "Show translation window near cursor",
            "closeAfterCopy": "Close translation window after copy",
            "clearTranslationHistory": "Clear Translation History",
            "advanced": "More options",
            "sourceLanguage": "Source language",
            "launchAtLogin": "Launch at login",
            "customProvider": "Custom Provider",
            "baseURL": "Base URL",
            "path": "Path",
            "model": "Model",
            "privacy": "Privacy",
            "apiKeysKeychain": "Keys are stored locally in secure Mac storage.",
            "historyLocal": "History is stored locally on this Mac. It is not synced or uploaded by JellyTranslate.",
            "clipboardFallback": "Clipboard is used only when needed to read selected text, then restored when possible.",
            "shareAnalytics": "Share anonymous usage analytics",
            "analyticsPrivacy": "Optional. JellyTranslate sends only anonymous events such as app launch, translation success/failure, provider, target language, and app version. It never sends selected text, translations, clipboard content, API keys, or window titles.",
            "analyticsNeedsAppID": "Analytics is active only in versions prepared with analytics settings.",
            "searchHistory": "Search recent translations",
            "recentTranslations": "Recent translations",
            "clearAll": "Clear All",
            "delete": "Delete",
            "historyOff": "History is off",
            "historyOffHelp": "Enable Save history in Settings to keep recent translations.",
            "noRecentTranslations": "No recent translations",
            "noRecentTranslationsHelp": "Translations you save will appear here.",
            "noResults": "No results",
            "noResultsHelp": "Try a different search.",
            "mock": "Mock",
            "openAI": "OpenAI",
            "custom": "Custom",
            "libreTranslate": "LibreTranslate",
            "libreTranslateKey": "LibreTranslate API key (optional)",
            "libreTranslateHint": "LibreTranslate support is planned for a future version.",
            "libreTranslateProvider": "LibreTranslate Provider",
            "myMemory": "MyMemory",
            "myMemoryHint": "Free service for first tests. No account or key required. Optional email can increase the daily free limit.",
            "contactEmail": "Contact email",
            "optional": "Optional",
            "deepLComingSoon": "DeepL - Coming soon",
            "appLanguage": "App Language",
            "keySaved": "Key saved",
            "keyCleared": "Key cleared",
            "copied": "Copied",
            "replaced": "Replaced",
            "currentAdvancedProvider": "Current service is selected in More options."
        ],
        .russian: [
            "quickStart": "Быстрый старт",
            "settings": "Настройки",
            "history": "История",
            "quit": "Выйти",
            "original": "Оригинал",
            "translation": "Перевод",
            "copy": "Копировать",
            "replace": "Заменить",
            "speak": "Озвучить",
            "openSettings": "Открыть настройки",
            "needsAttention": "Нужно внимание",
            "working": "Работаю",
            "translating": "Перевожу...",
            "emptySelection": "Текст не выделен",
            "emptySelectionHelp": "Выделите текст в любом приложении и нажмите хоткей JellyTranslate.",
            "testMode": "Только для теста. Настоящий перевод не выполняется.",
            "test": "Тест",
            "permissionNeeded": "Нужно разрешение",
            "permissionNeededMessage": "JellyTranslate нужно разрешение Accessibility, чтобы читать выделенный текст. Откройте Privacy & Security и включите JellyTranslate.",
            "copyFallbackFailed": "JellyTranslate не смог прочитать выделенный текст",
            "noSelectedText": "Текст не выделен",
            "providerTimeout": "Провайдер не ответил",
            "providerSetup": "Настройте сервис перевода",
            "translationFailed": "Перевод не удался",
            "welcomeTitle": "Добро пожаловать в JellyTranslate",
            "welcomeText": "Выделите текст в любом приложении, нажмите хоткей и сразу получите перевод.",
            "welcomeNote": "Без аккаунтов и длинного тура. Только то, что нужно для перевода по хоткею.",
            "permissions": "Разрешения",
            "permissionsText": "JellyTranslate нужно разрешение Mac, чтобы читать выделенный текст и по возможности заменять его.",
            "accessibility": "Accessibility",
            "granted": "Разрешено",
            "notGranted": "Не разрешено",
            "openPrivacy": "Открыть Privacy & Security",
            "checkAgain": "Проверить снова",
            "permissionRefreshHint": "Если переключатель уже зелёный, но здесь всё ещё написано «Не разрешено», закройте и откройте JellyTranslate заново. Иногда macOS применяет Accessibility после перезапуска.",
            "provider": "Сервис перевода",
            "providerText": "Выберите, откуда брать перевод. MyMemory работает уже сейчас без аккаунта; остальные сервисы появятся позже.",
            "openAIKey": "API-ключ OpenAI",
            "saveKey": "Сохранить ключ",
            "keyStored": "Ключ хранится локально в защищённом хранилище Mac.",
            "customInSettings": "Пользовательские сервисы появятся позже.",
            "tryIt": "Попробуйте",
            "tryItText": "Выделите любой текст и нажмите хоткей, чтобы перевести.",
            "privacyShort": "Выделенный текст отправляется только когда вы сами запускаете перевод.",
            "back": "Назад",
            "continue": "Дальше",
            "finish": "Готово",
            "translationSettings": "Перевод",
            "targetLanguage": "Язык перевода",
            "hotkey": "Хоткеи",
            "primaryHotkey": "Показать перевод",
            "secondaryHotkey": "Перевести и заменить",
            "resetHotkeys": "Сбросить хоткеи",
            "recordHotkey": "Нажмите сочетание...",
            "reservedHotkeyWarning": "Это привычное сочетание macOS. Лучше выбрать другое, чтобы избежать случайных действий.",
            "behavior": "Поведение",
            "saveHistory": "Сохранять историю",
            "showPopupNearCursor": "Показывать окно перевода рядом с курсором",
            "closeAfterCopy": "Закрывать окно перевода после копирования",
            "clearTranslationHistory": "Очистить историю переводов",
            "advanced": "Дополнительно",
            "sourceLanguage": "Исходный язык",
            "launchAtLogin": "Запускать при входе",
            "customProvider": "Custom Provider",
            "baseURL": "Base URL",
            "path": "Path",
            "model": "Модель",
            "privacy": "Приватность",
            "apiKeysKeychain": "Ключи хранятся локально в защищённом хранилище Mac.",
            "historyLocal": "История хранится только на этом Mac. JellyTranslate её не синхронизирует и не загружает.",
            "clipboardFallback": "Буфер обмена используется только когда это нужно для чтения выделенного текста, затем по возможности восстанавливается.",
            "shareAnalytics": "Отправлять анонимную аналитику использования",
            "analyticsPrivacy": "Необязательно. JellyTranslate отправляет только анонимные события: запуск приложения, успешный или неуспешный перевод, провайдер, язык перевода и версию приложения. Выделенный текст, перевод, буфер обмена, API-ключи и названия окон не отправляются.",
            "analyticsNeedsAppID": "Аналитика заработает только если в сборке настроены TelemetryDeck App ID и namespace.",
            "searchHistory": "Поиск по истории",
            "recentTranslations": "Недавние переводы",
            "clearAll": "Очистить всё",
            "delete": "Удалить",
            "historyOff": "История выключена",
            "historyOffHelp": "Включите «Сохранять историю» в настройках, чтобы сохранять новые переводы.",
            "noRecentTranslations": "История пуста",
            "noRecentTranslationsHelp": "Сохранённые переводы появятся здесь.",
            "noResults": "Ничего не найдено",
            "noResultsHelp": "Попробуйте другой запрос.",
            "mock": "Mock",
            "openAI": "OpenAI",
            "custom": "Custom",
            "libreTranslate": "LibreTranslate",
            "libreTranslateKey": "API-ключ LibreTranslate (необязательно)",
            "libreTranslateHint": "Поддержка LibreTranslate планируется в будущей версии.",
            "libreTranslateProvider": "LibreTranslate Provider",
            "myMemory": "MyMemory",
            "myMemoryHint": "Бесплатный сервис для первых тестов. Аккаунт и ключ не нужны. Email можно добавить позже, чтобы увеличить дневной лимит.",
            "contactEmail": "Email для лимита",
            "optional": "Необязательно",
            "deepLComingSoon": "DeepL — скоро",
            "appLanguage": "Язык интерфейса",
            "keySaved": "Ключ сохранён",
            "keyCleared": "Ключ удалён",
            "copied": "Скопировано",
            "replaced": "Заменено",
            "currentAdvancedProvider": "Текущий сервис выбран в разделе «Дополнительно»."
        ]
    ]
}
